apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: metro-kafka
  namespace: metro
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    # Use Kafka version supported by Strimzi (4.0.0, 4.0.1, 4.1.0, 4.1.1)
    version: "4.0.0"
    metadataVersion: "4.0-IV3"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
