apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: metro-kafka
  namespace: metro
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    # version: 3.7.0
    # Use Kafka version supported by latest Strimzi (4.0.0+)
    version: "4.0.0"
    metadataVersion: "4.0-IV3"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    resources:
      requests:
        memory: 512Mi
        cpu: "500m"
      limits:
        memory: 768Mi
        cpu: "1000m"
    jvmOptions:
      -Xms: 512m
      -Xmx: 768m
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "500m"
        limits:
          memory: 768Mi
          cpu: "1000m"
      jvmOptions:
        -Xms: 256m
        -Xmx: 512m
